name: irosu
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flame_bloc: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flame_behaviors: ^0.1.0

dev_dependencies:
  flame_lint: ^0.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/background/
